needs testing

diff --git a/scripts/install.sh.tmpl b/scripts/install.sh.tmpl
--- a/scripts/install.sh.tmpl
+++ b/scripts/install.sh.tmpl
@@ -125,8 +125,18 @@ function install {
 	fi
 	#move into PATH or cwd
 	chmod +x $TMP_BIN || fail "chmod +x failed"
-	{{ if .SudoMove }}echo "using sudo to move binary..."{{ end }}
-	{{ if .SudoMove }}sudo {{ end }}mv $TMP_BIN $OUT_DIR/$PROG || fail "mv failed" #FINAL STEP!
+	#move without sudo
+	OUT=$(mv $TMP_BIN $OUT_DIR/$PROG 2>&1)
+	STATUS=$?
+	# failed and string contains "permission denied"
+	if [ $STATUS -ne 0 ]; then
+		if [[ $OUT =~ "permission denied" ]]; then
+			echo "mv with sudo..."
+			sudo mv $TMP_BIN $OUT_DIR/$PROG || fail "mv failed" 
+		else
+			fail "mv failed"
+		fi
+	fi
 	echo "{{ if .MoveToPath }}Installed at{{ else }}Downloaded to{{ end }} $OUT_DIR/$PROG"
 	#done
 	cleanup
