support bz2 archives

diff --git a/scripts/install.sh.tmpl b/scripts/install.sh.tmpl
--- a/scripts/install.sh.tmpl
+++ b/scripts/install.sh.tmpl
@@ -101,8 +101,11 @@ function install {
 		GZURL="$GH/releases/download/$RELEASE/$NAME"
 		#gz download!
 		bash -c "$GET $URL" | gzip -d - > $PROG || fail "download failed"
+	elif [[ $FTYPE = ".tar.bz" ]] || [[ $FTYPE = ".tar.bz2" ]]; then
+		which tar > /dev/null || fail "tar is not installed"
+		which bzip2 > /dev/null || fail "bzip2 is not installed"
+		bash -c "$GET $URL" | tar jxf - || fail "download failed"
 	elif [[ $FTYPE = ".tar.gz" ]] || [[ $FTYPE = ".tgz" ]]; then
-		#check if archiver progs installed
 		which tar > /dev/null || fail "tar is not installed"
 		which gzip > /dev/null || fail "gzip is not installed"
 		bash -c "$GET $URL" | tar zxf - || fail "download failed"
